// AUTO-GENERATED by program/scripts/gen-defs.js - DO NOT EDIT BY HAND.
// Source of truth: program/programs/lumberjack/src/constants.rs (TOWER_DEFS,
// ENEMY_DEFS, BOSS_WAVE_INTERVAL) and .../state/td_board.rs (TOWER_KIND_*,
// ENEMY_KIND_*). Re-run `pnpm gen:defs` in program/ after changing the Rust
// balance tables.

export interface TowerDef {
  cost: number
  rangeSubtiles: number
  damage: number
  cooldownTicks: number
  splashRadiusSubtiles: number
  upgradeCost: number
  upgradeDamageBonus: number
  upgradeRangeBonus: number
  maxLevel: number
}

// Tower kind ids (kind 0 = NONE / empty slot).
export const TOWER_KIND_NONE = 0
export const TOWER_KIND_BASIC = 1
export const TOWER_KIND_SPLASH = 2

// Balance rows indexed by (kind - 1), mirroring the Rust TOWER_DEFS order.
export const TOWER_DEFS: readonly TowerDef[] = [
  {
    cost: 60,
    rangeSubtiles: 768,
    damage: 8,
    cooldownTicks: 6,
    splashRadiusSubtiles: 0,
    upgradeCost: 50,
    upgradeDamageBonus: 7,
    upgradeRangeBonus: 256,
    maxLevel: 3,
  },
  {
    cost: 100,
    rangeSubtiles: 512,
    damage: 6,
    cooldownTicks: 9,
    splashRadiusSubtiles: 256,
    upgradeCost: 70,
    upgradeDamageBonus: 5,
    upgradeRangeBonus: 256,
    maxLevel: 3,
  },
]

// Look up a tower kind's balance row. Returns undefined for NONE / unknown kinds.
export function towerDef(kind: number): TowerDef | undefined {
  return TOWER_DEFS[kind - 1]
}

// --- Enemies -------------------------------------------------------------

export interface EnemyDef {
  hp: number
  speedSubtiles: number
  reward: number
  radiusPx: number
}

// Enemy kind ids (row index into ENEMY_DEFS; NORMAL == 0).
export const ENEMY_KIND_NORMAL = 0
export const ENEMY_KIND_FAST = 1
export const ENEMY_KIND_STRONG = 2
export const ENEMY_KIND_BOSS = 3

// A boss is added on every Nth wave (0-indexed): waves 4, 9, 14, ...
export const BOSS_WAVE_INTERVAL = 5

// Base (wave-0) stats per enemy kind, indexed by kind id. Per-wave growth is
// applied on top by the sim (see tdSim.ts).
export const ENEMY_DEFS: readonly EnemyDef[] = [
  {
    hp: 36,
    speedSubtiles: 22,
    reward: 7,
    radiusPx: 10,
  },
  {
    hp: 22,
    speedSubtiles: 40,
    reward: 6,
    radiusPx: 8,
  },
  {
    hp: 90,
    speedSubtiles: 14,
    reward: 14,
    radiusPx: 12,
  },
  {
    hp: 400,
    speedSubtiles: 12,
    reward: 80,
    radiusPx: 16,
  },
]

// Look up an enemy kind's balance row. Unknown ids fall back to NORMAL (0).
export function enemyDef(kind: number): EnemyDef {
  return ENEMY_DEFS[kind] ?? ENEMY_DEFS[0]
}
